name: ui_book
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_bloc: ^8.1.1

  go_router: ^5.0.5

  url_launcher: ^6.1.6

  entity_book:
    path: ../../entity/entity_book

  domain_book:
    path: ../../domain/domain_book

  assets:
    path: ../../library/assets
  cubit_utils:
    path: ../../library/cubit_utils
  result_util:
    path: ../../library/result_util
  components:
    path: ../../library/components
  localization:
    path: ../../library/localization

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  test_utils:
    path: ../../library/test_utils

flutter:
  assets:
    - asset/image/