// DON'T EDIT THE CODE.
// This code generated by lib localization.
import 'package:localization/localization.dart';
import 'package:ui_book/src/locale/book_locale_resource.dart';

class BookLocale extends GoatLocale {
  BookLocale([String? languageCode]) : super(languageCode);
  
  String get bookListTitle {
    return resource.get('bookListTitle');
  }
  
  String get somethingWrong {
    return resource.get('somethingWrong');
  }
  
  String get checkConnection {
    return resource.get('checkConnection');
  }
  
  String get retry {
    return resource.get('retry');
  }
  
  @override
  LocaleResource get resource {
    return BookLocaleResource(languageCode);
  }
}
