// DON'T EDIT THE CODE.
// This code generated by lib localization.
import 'package:localization/localization.dart';

class BookLocaleResource extends LocaleResource {
  BookLocaleResource(String? languageCode) : super(languageCode);
  
  @override
  Map<String, Map<String, String>> get data => {
    'bookListTitle': {
      'default': 'List of Books',
    },
    'somethingWrong': {
      'default': 'Something went wrong..',
    },
    'checkConnection': {
      'default': 'Please check your connection, make sure it is connected.',
    },
    'retry': {
      'default': 'Retry',
    },
  };
}
