// DON'T EDIT THE CODE.
// This code generated by lib localization.
import 'package:flutter/material.dart';
import 'package:ui_book/src/locale/book_locale.dart';

class BookLocaleDelegate extends LocalizationsDelegate<BookLocale> {
  @override
  bool isSupported(Locale locale) => true;

  @override
  Future<BookLocale> load(Locale locale) async {
    return BookLocale(locale.languageCode);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<BookLocale> old) => false;
}
