name: domain_book
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  entity_book:
    path: ../../entity/entity_book
  networking:
    path: ../../library/networking
  service_locator:
    path: ../../library/service_locator

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0